### ISSUE TITLE
Just an error

### ISSUE THREAD

**Issue by Mehanik511** [madbomb122/BlackViperScript#1]
I have all needed updates, (10pro/1703/15063.138/64bit) and all files from github, setting execution policy or running batch file from admin - no effects. PS show me just red Error. Can you help me?
![powershell_2017-04-23_13-18-19](https://cloud.githubusercontent.com/assets/4943520/25312645/59279dc2-2827-11e7-9c0c-84c7393c198c.png)

**Comment by madbomb122** [comment]
does this show when you run the script or when you try one of the options?

do you have any values in the script change?

**Comment by Mehanik511** [comment]
https://cdn-e2.streamable.com/video/mp4/zmzvp.mp4?token=1494176030_77a8e71217430f6a5527c493ca3b858f2485d6bc
I don't understand second question, sorry. There is video with script executing.

**Comment by madbomb122** [comment]
i just added a test version (it's in the test folder). download and try that.

on the error screen (if it shows) will give me the info i need to help

**Comment by Mehanik511** [comment]
![image](https://cloud.githubusercontent.com/assets/4943520/25315917/02fce80a-2866-11e7-8472-289bd4073905.png)
Edition problem? This Windows setup version was russian in default and then i install English as system language. Maybe this causes problems...

**Comment by madbomb122** [comment]
i see the problem.. the edition checks for.. never realized it wouldnt work on non english versions
"Microsoft Windows 10 Home"
"Microsoft Windows 10 Pro"

doing some quick changes.. should be done in a min or 2

**Comment by madbomb122** [comment]
should be fixed now.. you can download the test or non test one

**Comment by Mehanik511** [comment]
Nicely done, man! It's work... "It's Alive!!!" ©

**Comment by madbomb122** [comment]
np and thanks for letting me know about the issue..
also i mentioned you in the new changelog as a thanks
