### ISSUE TITLE
Found possibly two spelling errors..

### ISSUE THREAD

**Issue by bubbismith** [madbomb122/BlackViperScript#12]
I saw this one in the CSV file, was it "Generated" or as is?
GernetatedByMadBomb122

Then while looking for info on changing an entry in the CSV  I found this in the topic I was looking for:
(# is fime)

probable a # sign is 'fine' and works as a comment... :-)

cheers, thanks for your work and efforts...
Bubbi

**Comment by madbomb122** [comment]
thanks for letting me know about the spelling errors.. im gonna leave the one in the CSV as is (until next big update), if i do change it i'll have to fix it in the script too. the script checks for that to make sure it's been downloaded right and dont want to force csv update (for just a typo) on people who use a newer script version

i fixed the "fime" in the readme
