### ISSUE TITLE
New Interface with easy Grid - I like...

### ISSUE THREAD

**Issue by bubbismith** [madbomb122/BlackViperScript#15]
Thanks for the excellent update, the new grid is very helpful and easy to set the options we want. 

Well Done!

I'm an old school VFP developer and we have an option we can set:
_TOOLTIPTIMEOUT = 0 && Until Mouse is Moved

This option allows the tool tip text to stay out until the mouse is moved off the control. That would be a very helpful option when reading some of the longer grid item / option explanations.

Cheers to a excellent program.

thanks very much.

bubbi

**Comment by madbomb122** [comment]
Thanks glad you like it.

This will be changed in the next release.. tooltips should now show till the mouse is not over the item anymore
