### ISSUE TITLE
1803?

### ISSUE THREAD

**Issue by wcrlewis** [madbomb122/BlackViperScript#16]
Does the index page note mean it isn't compatible?

**Comment by madbomb122** [comment]
still waiting on the services from black viper. he hasn't had the time to actually update the services yet.. but I have run the script on a virtual machine of 1803 and it works with what is used for 1706, and it doesn't seem to cause any problems.

**Comment by youurayy** [comment]
i would also love to see this -- BV's [page](http://www.blackviper.com/service-configurations/black-vipers-windows-10-service-configurations/) explicitly states that 1803 is supported, and then links to this repo to get it going -- and the first thing in this repo is a message that it's not supported yet == confusing.

**Comment by madbomb122** [comment]
blackviper made a mistake and didnt put an update on his page.. he has had stuff come up and hasn't been able to do the update.. last i herd from him he should have the update there today.. and depending on what is changed and how busy i am, the script should support 1803's services within a few days

**Comment by madbomb122** [comment]
Black viper should have his updated services sometime today.. i'll try to get my script updated within the next 2 days
