### ISSUE TITLE
Please add an option to bypass desktop/laptop check

### ISSUE THREAD

**Issue by ghost** [madbomb122/BlackViperScript#17]
**Is your feature request related to a problem? Please describe.**
Yes and I am frustrated when i want to experiment with the tweaked services but it detects my pc as laptop and blocks me from selecting the tweaked option.

**Describe the solution you'd like**
I want an option to bypass this check.

**Describe alternatives you've considered**
I considered deleting the script and attempting to edit the code myself to add this feature in.

**Additional context**
Not Applicable

**Comment by madbomb122** [comment]
So you want me to add an option so you can use the desktop's tweak option?
I'll think about adding this..

but for now what you can do is edit line 1849 (the text bellow)
` If($PCType -ne 2){ $Script:IsLaptop = '-Desk' } Else{ $Script:IsLaptop = '-Lap' }`
to
` $Script:IsLaptop = '-Desk' `
But so you know this will make it so it will use the desktop option for safe setting too

**Comment by ghost** [comment]
thanks the edit to the code allowed me to use the tweaked service config.

**Comment by madbomb122** [comment]
Option Has been added, so you wont need to change that line.. however it's something you will need to enable each time you start the script

**Comment by ghost** [comment]
thanks.

**Comment by ghost** [comment]
I had to reinstall windows shortly after altering my services. weirdly attempting to restore the services didn't work. it may be the result of system corruption idk. Im glad i had windows 10 april 2018 creators update on a usb and that i didnt have anything to backup.
