### ISSUE TITLE
Modifying Services List

### ISSUE THREAD

**Issue by bubbismith** [madbomb122/BlackViperScript#18]
I'm unable to modify the Services List.

On the options tab I select "ALL"
  and "Tweaked" Services Configuration

Go to Services List tab
  click Load Services
  The services appear as expected

Next click "Customize Service"
   Try to select an item in the grid
... Get endless Windows spinning wheel

   Often the grid disappears
   or the grid goes white, unresponsive, then maybe disappears...

   Can't change any of the options (deselect or change the Setting

One must "Hard close" the program.

Also, when the grid goes off, Task Manager show Windows Power Shell using 10% of the CPU. Must be an endless loop somewhere in the code.

Perhaps it's me, if so, let me know where I've gone wrong.

Bub

PS: Thanks for the sticky tool tip texts they work well...

Running Windows 1803, script 5.0.1, Service 4.0

**Comment by madbomb122** [comment]
Thanks for letting me know, i'll look into this

**Comment by madbomb122** [comment]
The problem has been fixed and has been released. i gave a thanks to you in changelog, if you want me to remove that let me know

**Comment by bubbismith** [comment]
Looks Good! All working well for me on both a 1709 and 1803, thanks very much! - bub
