### ISSUE TITLE
Cannot find files

### ISSUE THREAD

**Issue by Gigi4444** [madbomb122/BlackViperScript#20]
I had to change the line 149 so the script can find the files. It was : 
$Script:filebase = $PSScriptRoot + '\'

I did change it for : 
$Script:filebase = $PSScriptRoot + '.\'

**Comment by madbomb122** [comment]
what was your script directory path (full path) when you ran the script?
also what files could not be found?

**Comment by madbomb122** [comment]
btw, next time you post cost make sure to mark it as code.. `/` doesnt seem to show up otherwise

**Comment by madbomb122** [comment]
If the issue was because you have a symbol in the path it has been fixed.
