### ISSUE TITLE
some menu settings not being saved on exit / restart

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#21]
**Describe the bug**
the following settings from the ui menus are not being saved on exit or are reset each time the tool is launched:

- on tab "Services Options" -> "Black Viper Configuration Options (BV Services Only) -> the setting on the checkboxes "All" or "Min" is not being saved, setting on "Service Configurations" not being saved

- on tab "Script Options", setting on checkboxes "Auto Service Update", "Show Console Window" not being saved

**To Reproduce**
1. Set the Settings from the above description.
2. Quit and Restart Tool
3. Check wether settings have been saved in the ui

**Expected behavior**
Settings on the ui should be saved.

**Screenshots**
https://imgur.com/a/VWzYdVr

**Desktop (please complete the following information):**
 windows 10 pro 64 bit

**Additional context**
 - Script Version: 5.1.1 (july 30 2018) stable
- service version: 4.0 (may 29 2018)
 - Release Type: stable

**Comment by madbomb122** [comment]
i never intended the service options to be saved, but i guess i can add it.

i'll take a look into the other 2 also, thanks for letting me know

**Comment by madbomb122** [comment]
Thanks,
The issue has been fixed and script is now updated with fix v5.1.2
also gave a thanks in the changelog

**Comment by zoulztealer** [comment]
cool, thanks!
