### ISSUE TITLE
Crash on mouse-wheel-scroll in enabled/disabled jump-list

### ISSUE THREAD

**Issue by 01der** [madbomb122/BlackViperScript#22]
**Describe the bug**
The script crashes when mouse-wheel scrolling while having any enabled/disabled jump-list selected. 

**To Reproduce**
1. Go to 'Service Options'
2. Choose 'Service Configurations: Safe'
3. Go to 'Services List'
4. Click on 'Load Services'
5. Choose any field in the 'Black Viper'-column 
6. Scroll up and down with mouse-wheel
7. See error

**Expected behavior**
Changing of field-value, at least no crash.

**Desktop (please complete the following information):**
 - OS Version: Win 10 Edu (Fall Creators Update)

**Additional context**
 - Script Version: 5.1.2

**Comment by madbomb122** [comment]
I know about this issue it only happens if you select something then use the mouse wheel

However the only way to fix this currently is to 
1. Remove the colors showing when you change something
2. Disable selecting of items

I am still trying to find another solution

**Comment by madbomb122** [comment]
The issue should now be fixed in v5.2.1 -which is released.
If the issue still shows up please reopen issue, thanks
