### ISSUE TITLE
kill, modify, restore processes with list

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#23]
**Is your feature request related to a problem? Please describe.**
would it be possible that the tool gets a function to not only kill, load and save (windows) services to and from a customizable list, but to also do that with a list of all running processes i can see in the task manager.

thing is, every time my pc boots up, i want to kill or launch a few other windows services as well as other processes by 3. party tools, like steam, battle.net, origin, driverbooster, useless wlan utilities from the driver, etc. etc. which i have to do manually via task manager.

**Describe the solution you'd like**
after i killed all unwanted windows and other processes manually by task manager and / or blackviperscript, i want to save and eventually reload that state manually or automatically on or after the next reboot via a "process profile".

**Describe alternatives you've considered**
some type of process manager. not sure if any exists that can do this.

**Additional context**

**Comment by madbomb122** [comment]
From what I am understanding of what you want.. You want something that can Run and Kill running processes based on your preferences.

If this is what you I can help you make a script that can do something like this. But I wont be adding it to this script.

**Comment by zoulztealer** [comment]
thats cool! yeah, not sure if you looked at process lasso and i dont know what it really can do with its profiles, but something that direction.

**Comment by madbomb122** [comment]
i created a simple script
[https://github.com/madbomb122/StartStop](https://github.com/madbomb122/StartStop)

i havnt tested it yet, but make sure to look @ the readme

**Comment by zoulztealer** [comment]
wow ... nice, thats pretty much what i wanted. will test now.

**Comment by zoulztealer** [comment]
not sure, if im doing anything wrong here, but i get this from it:

```
> + StartStop.ps1
> + ~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (StartStop.ps1:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
```

im running the script from cmd terminal admin rights and: powershell StartStop.ps1

when ran from powershell something else happens:

```
> + .\StartStop.ps1
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
```

```
> + .\StartStop.ps1 -list
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by madbomb122** [comment]
for the from cmd, you are doing it wrong.. i think

as for from powershell, you need to allow unsigned script to run it from there, you need to use following command first 
`Set-ExecutionPolicy -ExecutionPolicy Unrestricted`
or
`Set-ExecutionPolicy -ExecutionPolicy Bypass`


i did add a bat file you can use to run it now too (w/o having to use the command above)

**Comment by zoulztealer** [comment]
running the bat file gives me this:

```
> + If(!(Test-Path -LiteralPath $Filename -PathType Leaf)) {
> +                             ~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
>    PathCommand
```
ive set bypass policy but in powershell also this when i run without option / argument:

```
> + If(!(Test-Path -LiteralPath $Filename -PathType Leaf)) {
> +                             ~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
>    PathCommand
```

but running with argument list now works in powershell, i can see all services running.

what file type does the list has to be? can you add a save all running processes to list option?

**Comment by madbomb122** [comment]
you need to create a list for it to use and tell the script what file to use..
please note that

about stopping:
you give just the name of process

about starting:
you have to give full path + name

so you will need separate files and will need to tell the script if you want to start or stop

**Comment by zoulztealer** [comment]
created a txt stop file containing:

```
> Everything
> Everything
```
everything search tool, has two processes running:

Everything             C:\Program Files\Everything\Everything.exe
Everything             C:\Program Files\Everything\Everything.exe

gave me this:

```
> PS C:\Users\intel\Downloads\StartStop-master (1)\StartStop-master> .\StartStop.ps1 -stop -F stoplist.txt
> Stopping Everything
> Stop-Process : Der Parameter "InputObject" kann nicht gebunden werden. Der Wert "Everything" vom Typ "System.String"
> kann nicht in den Typ "System.Diagnostics.Process" konvertiert werden.
> In C:\Users\intel\Downloads\StartStop-master (1)\StartStop-master\StartStop.ps1:36 Zeichen:16
> +         Stop-Process $Proc
> +                      ~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Stop-Process], ParameterBindingException
>     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.StopProcessCommand
> 
> Stopping Everything
> Stop-Process : Der Parameter "InputObject" kann nicht gebunden werden. Der Wert "Everything" vom Typ "System.String"
> kann nicht in den Typ "System.Diagnostics.Process" konvertiert werden.
> In C:\Users\intel\Downloads\StartStop-master (1)\StartStop-master\StartStop.ps1:36 Zeichen:16
> +         Stop-Process $Proc
> +                      ~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Stop-Process], ParameterBindingException
>     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.StopProcessCommand
```

**Comment by madbomb122** [comment]
try downloading the updated script file.. it should work now.
i tested starting and stopping, it works for me

**Comment by zoulztealer** [comment]
works top now. is there a possibility to confirm all  ("yes to all") requests from the powershell via the script already or make it so, that it doesnt ask for confirmation?

```
> PS C:\Users\intel\Downloads\StartStop-master (2)\StartStop-master> .\StartStop.ps1 -stop -F .\stoplist.txt
> Stopping ASCService
> 
> Bestätigung
> Möchten Sie den Vorgang "Stop-Process" wirklich für das folgende Element ausführen: ASCService(1424)?
> [J] Ja  [A] Ja, alle  [N] Nein  [K] Nein, keine  [H] Anhalten  [?] Hilfe (Standard ist "J"): A
> Stopping Calculator
> Stopping drivermax
> Stopping drivermax
> Stopping gjagent
> Stopping innostp
> Stopping Microsoft.Photos
> Stopping Music.UI
> Stopping PubMonitor
> Stopping runSW
> 
> Bestätigung
> Möchten Sie den Vorgang "Stop-Process" wirklich für das folgende Element ausführen: runSW(3936)?
> [J] Ja  [A] Ja, alle  [N] Nein  [K] Nein, keine  [H] Anhalten  [?] Hilfe (Standard ist "J"): A
> Stopping SkypeHost
> Stopping SwUSB
> 
> Bestätigung
> Möchten Sie den Vorgang "Stop-Process" wirklich für das folgende Element ausführen: SwUSB(4828)?
> [J] Ja  [A] Ja, alle  [N] Nein  [K] Nein, keine  [H] Anhalten  [?] Hilfe (Standard ist "J"): A
> Stopping UninstallMonitor
> Stopping WinStore.App
```

i see from task manager there are basically two ways to kill a process "end task" and "end process structure". what type of termination does your script use? can you make it use "end process structure", too?

regards and many thanks for your awesome work!

ps: 

running the bat gives me this in cmd terminal and powerhsell and i believe it cant take the arguments:

```
> PS C:\Users\intel\Downloads\StartStop-master (2)\StartStop-master> .\_StartStop.bat -list
> "Running StartStop.ps1"
> Test-Path : Das Argument kann nicht an den Parameter "LiteralPath" gebunden werden, da es sich um eine leere
> Zeichenfolge handelt.
> In C:\Users\intel\Downloads\StartStop-master (2)\StartStop-master\StartStop.ps1:24 Zeichen:29
> + If(!(Test-Path -LiteralPath $Filename -PathType Leaf)) {
> +                             ~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
>    PathCommand
> 
> PS C:\Users\intel\Downloads\StartStop-master (2)\StartStop-master> .\_StartStop.bat
> "Running StartStop.ps1"
> Test-Path : Das Argument kann nicht an den Parameter "LiteralPath" gebunden werden, da es sich um eine leere
> Zeichenfolge handelt.
> In C:\Users\intel\Downloads\StartStop-master (2)\StartStop-master\StartStop.ps1:24 Zeichen:29
> + If(!(Test-Path -LiteralPath $Filename -PathType Leaf)) {
> +                             ~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
>    PathCommand
```

**Comment by madbomb122** [comment]
not sure if i can tell it to confirm.. but i will check

the script uses the powershell command `Stop-Process`, from what i know i cant have it to end process structure.

with the bat it doesnt accept the switches.. you have to go into the file and tell it what you want to pass to the script file.

**Comment by madbomb122** [comment]
i think i got it so it wont ask for confirm

**Comment by zoulztealer** [comment]
when i try to run the latest version it cant find the stoplist anymore although its there:

```
> .\stoplist.txt
> Not found
> 
> Press any key to exit:
```

```
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> dir
> 
> 
>     Verzeichnis: C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> ------       22.08.2018     20:58            798 README.md
> ------       22.08.2018     20:58           1442 StartStop.ps1
> -a----       23.08.2018     22:13            185 stoplist.txt
> ------       22.08.2018     20:58           1084 _StartStop.bat
> 
> 
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> .\StartStop.ps1 -F .\stoplist.txt -stop
```

i also dont understand the comments from the bat file. could you elaborate a bit more on how to use the bat and what it can do or if i have to set anything there?

**Comment by madbomb122** [comment]
```
:: Name of Script File
Set Script_File=StartStop.ps1 <--- Name of script file.. you dont need to change this

:: ProcFile is name of file you want to use
Set ProcFile=file.txt <--- Name of files you want script to run.. EX: 'stoplist.txt'
set File=no <--- If you want to use the file above (yes or no)

:: If you want to start or stop
:: Stop = Stop
:: Start = Run
Set StopStart=Stop <---- Do you want the script to Start(= Run) processes or Stop (= Stop) them


Set List=no <---- If you want the script to ONLY show list of running processes nothing else
```

**Comment by zoulztealer** [comment]
ok, your current version actually works. i didnt start powershell with admin rights or sth ... sorry!

i think i got a step further with the bat, but still not understanding it 💃 

```
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> Set ProcFile=stoplist.txt
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> Set File=no
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> set Script_File=StartStop.ps1
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> Set StopStart=Stop
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> Set List=no
> PS C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master> .\_StartStop.bat
> "Running StartStop.ps1"
> Test-Path : Das Argument kann nicht an den Parameter "LiteralPath" gebunden werden, da es sich um eine leere
> Zeichenfolge handelt.
> In C:\Users\intel\Downloads\StartStop-master (3)\StartStop-master\StartStop.ps1:24 Zeichen:29
> + If(!(Test-Path -LiteralPath $Filename -PathType Leaf)) {
> +                             ~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
>    PathCommand
```

maybe i did something wrong? i understand that i have to just set those variables in terminal before running the bat?

**Comment by madbomb122** [comment]
sigh.. you are supposed to edit the bat file and change those `Set` items.. so you can just double click the bat file and it will send the info to the script..

so instead of running script with all those switches, it will put in the correct switch information.

so if you wanted to run the script with your `stoplist.txt`
go into the bat and change
```
Set ProcFile=stoplist.txt

Set File=yes

Set StopStart=Stop
```
this is instead of running script with` -f stoplist.txt -stop`
and leave all the other items as is
if you wanted to start stuff with a list of `startlist.txt`
```
Set ProcFile=startlist.txt

Set File=yes

Set StopStart=Run
```
this is instead of running script with` -f startlist.txt -start`

btw if you just double click the bat with the setting in there.. it will launch the script as admin (but with the UAC prompt, if it's enabled)

**Comment by zoulztealer** [comment]
ok, finally figured it. 💃
