### ISSUE TITLE
Ability to change State of Service -Opinion

### ISSUE THREAD

**Issue by madbomb122** [madbomb122/BlackViperScript#25]
I would like people's opinion on if I should add the ability on the 'Service Table' tab to select if you want a service to be running or stopped.

If above is wanted, I may also add in the backup/save file the state in there to be loaded.. If it isnt annoying to implement.

**Edit:**
For anyone that wants to test out this new feature/Option [Save This](https://raw.githubusercontent.com/madbomb122/BlackViperScript/master/Testing/BlackViper-Win10.ps1)

**Comment by madbomb122** [comment]
I added the ability to change service state, but it's in the testing folder for anyone that wants to test/try it out

**Comment by zoulztealer** [comment]
yeah, sounds nice. id be for it.
