### ISSUE TITLE
update displays new script file but cant find any

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#26]
**Describe the bug**
when checked for updates via services & script, it is displayed that there is an update for the script file, but none can be found.

**To Reproduce**
1. check for updates with services & script
2. click on yes for update script file (5.2.2 to 5.2.3)
3. app returns there is no service update found

**Expected behavior**
app should update services and script.

**Screenshots**
![bvscript6](https://user-images.githubusercontent.com/42149920/44956076-65382e00-aebe-11e8-8cfc-cc34f349b35b.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Creator's Update]
 - OS Build: [e.g. Home]
 - Modded OS: [e.g. No] -If you are using an OS that has removed items using a program like Nlite

**Additional context**
 - Script Version: 5.2.2 (aug 28 2018) stable
- service version: 4.0 (may 29 2018)

**Comment by zoulztealer** [comment]
just updated to 5.2.3 on run script.

**Comment by madbomb122** [comment]
The 1st was for the Script, which there is an update for
The 2nd is for the service file, which you have the latest already

**Comment by madbomb122** [comment]
I did some check to make sure things are fine and it did lead to a bug i found, thanks

**Comment by zoulztealer** [comment]
nice.
