### ISSUE TITLE
not updating old version

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#28]
**Describe the bug**
console says it would relaunch the tool after update, but nothing happens.

**To Reproduce**
1. update to latest version from previous version (not working)
2. check console
3. check if tool relaunches after update / updated from inside app

**Expected behavior**
app should relaunch after update.

**Screenshots**
![bug](https://user-images.githubusercontent.com/42149920/45590622-a27bd180-b93c-11e8-9b8c-0a78a182fb75.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Creator's Update]
 - OS Build: [e.g. Home]
 - Modded OS: [e.g. No] -If you are using an OS that has removed items using a program like Nlite

**Additional context**
 - Script Version: 

 - Release Type: [e.g. Stable or Testing]

**Comment by madbomb122** [comment]
If you run the script.. it still the old version too..
If you read the notice i have on the readme.. it says the update on 5.2.4 (the version you have) is broken.

i even said it in the last issue you posted.
