### ISSUE TITLE
Infinite loop query about updating the 'BlackViper.cs' file

### ISSUE THREAD

**Issue by harmonicx** [madbomb122/BlackViperScript#29]
**Question**   
Did you look at ReadMe,FAQ or issues to see if issue is already posted or fixed?
Yes

**Describe the bug**   
I was trying to restore from a backup file using the Custom Setting option and browsed to my backup file. Then upon hitting the 'Run Script with Custom Service List' button, a dialog box with the following query is shown: The File 'BlackViper.csv' needs to be Updated. Do you want to download the file 'BlackViper.csv'?

This occurs even though prior to running the script, the 'BlackViper.csv' is present in the directory and clicking on the button to check for an update to the Services indicates that you have the latest version.

If you hit the 'Yes' button on the dialog box, the dialog box instantly closes and the same dialog box is presented again. This continues in an infinite loop till you hit the 'No' button.

At this point, if you check the backup file you were trying to restore from, you would notice that it has been overwritten with the contents of the 'BlackViper.csv' file.

**To Reproduce**   
1. Run _Win10-BlackViper.bat
2. Under Service Options tab, select Custom Setting in the Service Configurations drop-down list then browse to a backup file to restore
3. Click the 'Run Script with Custom Service List' button
4. The dialog box asking to update the 'BlackViper.csv' file should now appear
5. Clicking 'Yes' on the dialog box will result in an infinite loop with the same query

**Expected behavior**   
The script is executed and restores my Service Configuration according to the backup file

**Screenshots**
![image](https://user-images.githubusercontent.com/20717196/45595297-a9621d00-b9ec-11e8-8f51-a3d610af7017.png)
   
![image](https://user-images.githubusercontent.com/20717196/45595293-8a638b00-b9ec-11e8-8125-4434e2ca4461.png)

**Desktop (please complete the following information):**   
 - OS Version: April 2018 Update
 - OS Build: Pro
 - Modded OS: No

**Additional context**
 - Script Version: 5.3.0
 - Release Type: Stable

**Comment by madbomb122** [comment]
This issue is being looked into

**Comment by madbomb122** [comment]
The issue has been solved, and will be released shortly

**Comment by madbomb122** [comment]
The fix as been released in v5.3.1, if issue persists please re-open issue.
Thanks
