### ISSUE TITLE
Save Current button does not perform a save

### ISSUE THREAD

**Issue by harmonicx** [madbomb122/BlackViperScript#30]
**Question**   
Did you look at ReadMe,FAQ or issues to see if issue is already posted or fixed?
Yes

**Describe the bug**   
The Save Current button under the Services List tab does not actually produce a file.

**To Reproduce**   
1. Under the Services Options tab, select the Safe option from the Service Configurations drop-down list
2. Under the Services List tab, click the Load Services button, then click the Save Current button
3. Specify file name and its location under the Save As dialog box and hit the Save button
4. Specified file is not generated

**Expected behavior**   
Current Service Configuration is saved to the specified file

**Desktop (please complete the following information):**   
 - OS Version: April 2018 Update
 - OS Build: Pro
 - Modded OS: No

**Additional context**
 - Script Version: 5.3.0
 - Release Type: Stable

**Comment by madbomb122** [comment]
I fixed this issue, and will be released once i fix the other issue

**Comment by madbomb122** [comment]
The fix as been released in v5.3.1, if issue persists please re-open issue.
Thanks
