### ISSUE TITLE
dev log button has faulty logic, disables other checkboxes

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#31]
**Question**   
nope.

**Describe the bug**   
when the checkbox for dev log is ticked, it automatically sets a variety of other checkbox options enabled. when dev log is unticked again, those checkboxes remain ticked and become grayed out / disabled and thus cannot be edited again.

**To Reproduce**   
1. tick checkbox dev log in tab scipt options
2. untick checkbox
3. check behaviour of other checkboxes

**Expected behavior**   
checkboxes that become ticked along with ticking dev log checkbox should become unticked and available again, after dev log checkbox has been unticked again.

**Screenshots**   
![bug1](https://user-images.githubusercontent.com/42149920/45599993-dff06580-b9f5-11e8-81cb-c49f98b51d15.jpg)
![bug2](https://user-images.githubusercontent.com/42149920/45599994-e41c8300-b9f5-11e8-85ee-f08d6278d3ba.jpg)

**Additional context**
 - Script Version: 5.3.0
 - Release Type: 4.2

**Comment by madbomb122** [comment]
ugh, while doing somethings i switched the items around.. issue is fixed.. will be released when i fix other issue

**Comment by madbomb122** [comment]
issue fixed in v5.3.2 and script has been updated
