### ISSUE TITLE
Invalid .cvs file.

### ISSUE THREAD

**Issue by sleepyspider1** [madbomb122/BlackViperScript#33]
Run disabled, invalid cvs file.
Just run and load the .cvs file in this depot.

**Comment by madbomb122** [comment]
if you are trying to load the `blackviper.csv` file from the `custom settings` drop menu.. that is why

that is for csv files generated by the script

**Comment by madbomb122** [comment]
the `blackviper.csv` file is used for the other options `default, safe, tweaked`
