### ISSUE TITLE
No Saved Services List

### ISSUE THREAD

**Issue by bubbismith** [madbomb122/BlackViperScript#34]
I'm not sure I got this one right cause it seems obvious, but I'm running the newest version I just downloaded 5.3.7 and 4.2.

Service Options - All
  Select my custom settings which were from 5/21/2018
Services List - check Customize Service
  Made 1 change
Click - Save Selection
  Get Save As screen pointing to my Black-master folder on my desktop
  put in a file name
  Press <Save>
Get "File Saved" dialog with the correct path and file name
  expected to see a file there
  there was no saved file.

bubbi

**Comment by madbomb122** [comment]
yeah it's a bug.. i will fix this soon as i find the issue
thanks for letting me know

**Comment by madbomb122** [comment]
Issue is now fixed in V5.3.8 and the update has been posted
thanks again

**Comment by bubbismith** [comment]
Thanks mate, works good!
