### ISSUE TITLE
tool / script to manipulate protected tcp settings

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#35]
**Is your feature request related to a problem? Please describe.**   

this tool (https://www.speedguide.net/files/TCPOptimizer.exe) provides an easy way to change and manage windows' tcp settings related to ethernet adapters / wifi, etc. regrettably some of these settings are not being applied, because:

"Supposedly the netsh congestionprovider setting is deprecated and bugged under Windows 8/10, and one should use the Powershell cmdlets. Use at your own risk. Changing CTCP directly with netsh is not possible by default under Windows 8, the commands are still listed below for reference:"

https://www.speedguide.net/articles/windows-8-10-2012-server-tcpip-tweaks-5077

when ran from powershell it appears that the specific tcp settings are being write-protected by windows and thus cant be applied by the tool:

```
> PS C:\WINDOWS\system32> Set-NetTCPSetting -SettingName InternetCustom -CongestionProvider DCTCP
> Set-NetTCPSetting : Property CongestionProvider is read-only
> In Zeile:1 Zeichen:1
> + Set-NetTCPSetting -SettingName InternetCustom -CongestionProvider DCT ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (MSFT_NetTCPSett...ystemName = ""):ROOT/StandardCimv2/MSFT_NetTCPSettin
>    g) [Set-NetTCPSetting], CimException
>     + FullyQualifiedErrorId : Windows System Error 87,Set-NetTCPSetting
```

**Describe the solution you'd like**   
script / tool that can apply all the necessary tcp tweaks, that tcp optimizer from speed guide has got, too, effectively, among others: congestion control provider, windows scaling heuristics, tcp window auto tuning, tcp chimney offload specifically.

**Describe alternatives you've considered**   
registry, elevated command line and powershell cant do the job.

**Additional context**   
https://www.speedguide.net/images/tcp_optimizer/tcpo_v3.png

**Comment by madbomb122** [comment]
sorry this is not something i will do
