### ISSUE TITLE
running the script on tweaked / safe "disables" wifi, ethernet adapter / capability

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#36]
**Question**   
Did you look at ReadMe, FAQ or Issues to see if issue is already Known or Fixed?

i dont always.

**Describe the bug**   
when the script applies services configurations "tweaked" or "safe" with the option "all - change all services", the wifi adapter becomes kind of disabled after a reboot and cant be used anymore. it appears, that a certain, unknown service is causing this (no ip table allocation, driver / service not being loaded / blocked). the wifi becomes useable again, when the service configuration is reverted back with the "default" setting. it should be noted, that this may not happen necessarily on all hardware configurations or in all cases.

**To Reproduce**   
1. Go to github.com/madbomb122/BlackViperScript
2. Click download
3. extract zip
4. execute _win10-blackviper.bat with admin rights
5. select "all - change all services" and either "safe" or "tweaked" service configurations from tab "service options".
6. reboot, check for wifi adapter functionality and connectivity

**Expected behavior**   
wifi / ethernet should not be affected by this.

**Screenshots**   
![bug1](https://user-images.githubusercontent.com/42149920/49198326-dd65a100-f392-11e8-83d6-5d30e7c00847.png)
![bug2](https://user-images.githubusercontent.com/42149920/49198332-e191be80-f392-11e8-9fe3-a7a151d6c2da.png)

**Computer Information (Please complete the following information):**   
[DxDiag.txt](https://github.com/madbomb122/BlackViperScript/files/2627529/DxDiag.txt)

**Additional context**   
 - Script Version: 5.4.2 (this was also present in previous versions)
 - Release Type: stable
 - Run method:  via bat file from elevated powershell

regards

**Comment by madbomb122** [comment]
Edit: nm.. i think i see the problem

**Comment by madbomb122** [comment]
the issue is with how the services are configured.. the service `WlanSvc` is for wifi stuff which is being changed with the safe/tweaked settings on desktop.

try running the script and have it skip that service by unchecking it in the service list in the script.

let me know if that solved the problem.

**Comment by zoulztealer** [comment]
nice you got to the bottom of this. will report back on it asap.

edit: just ran the script and excluded the wlan service and it runs fine! consider it fixed. thank you very much.

**Comment by mattreecebentley** [comment]
This issue is back in most recent release. Wlansvc is disabled, at least under 1903.

**Comment by madbomb122** [comment]
This only gets changed on desktops.. that is how the service configuration was intended.

**Comment by mattreecebentley** [comment]
It shouldn't be - more desktops are connected via wifi nowadays than not. Irritating to have to change it back every time.

**Comment by madbomb122** [comment]
you have 2 options
1. edit the blackviper.csv file and change it in there (just look in the readme for the number meaning)
2. make your own service config file

**Comment by mattreecebentley** [comment]
Or you could set it to not change the wlansvc setting, since this is already at Manual in Win10 if there is no wifi adaptor present, to the best of my knowledge.

**Comment by madbomb122** [comment]
the problem with that is computers are having built in wifi cards and people dont use it, so the service setting that i have in the config wont be changed.

you can easily just change 
`WlanSvc,3,3,2,3,2`
to
`WlanSvc,3,3,3,3,3`
or just delete the line
