### ISSUE TITLE
1903 support

### ISSUE THREAD

**Issue by mattreecebentley** [madbomb122/BlackViperScript#38]
Currently the script quits on -auto -safe if Win10 1903 is the OS.
States that Max Recommended version is 1803, but that can't be right.

**Comment by madbomb122** [comment]
There is no TRUE support for anything higher than 1803 and lower than 1703 since there is no service configuration for them.

you have to use the **-sbc** switch with anything not in the range of 1703 to 1803

**Comment by mattreecebentley** [comment]
This was a feature request, so it's not user error.
If the configs work for 1809 and upwards (they do), then surely the check is unnecessary for those versions.

**Comment by madbomb122** [comment]
they may work on those version, but it does not mean it cant cause problems.. so this will not change w/o an official config has been done

**Comment by mattreecebentley** [comment]
Yeah, so... it's a feature request for that I guess.

**Comment by madbomb122** [comment]
sorry i will not be adding official 1903 support unless someone releases a good service config that i can use that is for 1903.. and i will not have it bypass the version check that can be done by the user
