### ISSUE TITLE
-lcsc option does not appear to work with -auto setting

### ISSUE THREAD

**Issue by mattreecebentley** [madbomb122/BlackViperScript#39]
**Question**   
Yes

**Describe the bug**   
-lcsc option does not appear to work with -auto setting. You need to specify '-safe' or -tweaked' to get -auto to work, which then override the csv file after -lcsc

**To Reproduce**   
Run script with -lcsc and -auto

**Expected behavior**   
Script should process options in csv file automatically without gui

**Comment by madbomb122** [comment]
i will take a look at this problem when i can

**Comment by madbomb122** [comment]
I tested this on my 2 computers and a VM and it works, all with different builds and it works fine.

you are specifying a file when you use **-lcsc** right?
example:
`.\blackviper-win10.ps1 -lcsc test.csv -auto -sbc`
or
`.\blackviper-win10.ps1 -lcsc c:\somefolder\test.csv -auto -sbc`

**Comment by mattreecebentley** [comment]
Yes, although the ordering of the command arguments was different, and I'm running it through the .bat, not directly through the powershell script

**Comment by madbomb122** [comment]
for the bat file you dont have to set auto or the blackviper to anything other than 0 and it works fine when you load a service config file.. however for some reason i did have to put the full path\file for the custom service config file to load.

**Comment by mattreecebentley** [comment]
Okay, so the bug is that the .bat file needs the full path

**Comment by madbomb122** [comment]
yup sorry about that,

**Comment by mattreecebentley** [comment]
All good, thank you-

**Comment by madbomb122** [comment]
i found the issue with the bat file needing full path of the config file and it is now fixed (in the ps1 file not the bat)
