### ISSUE TITLE
Hello! I used your script (for better ping on server) but it did it opiste way! from 20ms ping to 50ms! Is theres any way to undo this script or stop it?

### ISSUE THREAD

**Issue by SexBomb2000** [madbomb122/BlackViperScript#42]
**Question**   
Did you look at ReadMe, FAQ or Issues to see if issue is already Known or Fixed?

**Describe the bug**   

**To Reproduce**   

**Expected behavior**   

**Screenshots**   

**Computer Information (Please complete the following information):**   
 - OS Version: [e.g. Creator's Update]   
 - OS Build: [e.g. Home]   
 - Modded OS: [e.g. No] -If you are using an OS that has removed items using a program like Nlite   

**Additional context**   
 - Script Version: [e.g. 3.0.1]   
 - Release Type: [e.g. Stable or Testing]   
 - Run method:  [e.g. ps1 or bat file]   
 
 **If it is an issue with updates**   
 - Do you have the `update.bat` File? : [e.g. Yes]   
 - If above is **Yes**, What version is it? : [e.g. 1.3.4]

**Comment by madbomb122** [comment]
This should NOT have increased your ping.. your ping issue may not be service related but something else.

The script it not something that runs constantly in the background or anything like that
The only way to undo it is using the default or a backup setting (if you made one with script).

If you don't have a backup or the default setting doesnt work for you then, i cant help you
