### ISSUE TITLE
All or nothing either way... :-)

### ISSUE THREAD

**Issue by bubbismith** [madbomb122/BlackViperScript#5]
Hi, I'm having some issues. If I run the current 'stable' version it runs ok but produces no results. IE: it says the changes have been made, say to the xbox entries from manual -> disabled. But they don't change. If I run the test version I get the error below.  Any tips would be appreciated. Thanks. bub.

Changing Service Please wait...
Service_Name - Current -> Change_To 
-------------------------------------

Xbox Live Game Save (XblGameSave) - Manual -> Disabled
-Service : The term '-Service' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\T\bv2\BvTest.ps1:836 char:68
+ ...   If($ServiceTypeNum -In 1..4 -and $Dry_Run -ne 1) { -Service $Servic ...
+                                                          ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Service:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Xbox Live Networking Service (XboxNetApiSvc) - Manual -> Disabled
-------------------------------------
Service Changed...

**Comment by madbomb122** [comment]
Thanks for letting me know.. the problem should be fixed..
also I did a mention/thanks in changelog

**Comment by bubbismith** [comment]
Worked well, thanks very much!

**Comment by madbomb122** [comment]
glad to hear it, and np
also ty again for letting me know about the error
