### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by sdmunozsierra** [madbomb122/BlackViperScript#8]
Hi,

There is a small bug in line 659, it is missing an end  parentheses at the end.

Thank you!

**Comment by madbomb122** [comment]
Thanks, dunno how i missed that.. i always run it before i post it..
Gave you a thanks in changelog

Issue Fixed in v.3.7.2

**Comment by sdmunozsierra** [comment]
Hah it happens sometimes!
Thank you, gad to help 😄
