### ISSUE TITLE
Windows 10 v1709 OS Build 16299.19 Script Just closes

### ISSUE THREAD

**Issue by ghost** [madbomb122/BlackViperScript#9]
Currently with the latest Windows 10 build when you run the _Win10-BlackViper.bat it just instant closes and does nothing.

**Comment by ghost** [comment]
Okay, running BlackViper-Win10.ps1 instead ran the script fine.

**Comment by madbomb122** [comment]
I tested the script on the new version and it works fine for me.

If the ps1 file runs fine on it's own then i'm not sure why the bat did nothing for you.. all the bat file does it makes it easier to run the ps1 file with the switches and w/o having to bypass the script blocking Microsoft has by default.
